name=str((input("enter your name")).strip())
result=len(name)
print(f"lenght of string is  {result}")
#result1=name.find((input("enter what to find")).strip())
result1=name.find("n")
result2=name.rfind("n")
result3=name.capitalize()
result4=name.upper()
result5=name.isdigit()
result6=name.isalpha()
result7=name.count("n")
result8=name.replace(" ","-")
print(f"n from start {result1}")
print(f"n from last {result2}")
print(f"first letter in capital {result3}")
print(f"name in capital {result4}")
print(f"is name all digits? ans.{result5}")
print(f"is name all alphabet ans.{result6}")
print(f"n in name number is {result7}")
print(f"new name = {result8}") 
# string indexing 
print(name[0])
print(name[0:5])
print(name[-1])
print(name[::3]) #print every element at a gap of 3
